# Port aplikacji RentalService. MovieService musi być na 8081 (patrz application.yml MovieService).
spring.application.name=RentalService
server.port=8082

# Adres Swagger UI: http://localhost:8082/swagger-ui.html
# Specyfikacja OpenAPI (JSON): http://localhost:8082/v3/api-docs
